@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-left-> "1" UniquePersonList
AddressBook *-right-> "1" UniqueJobList

UniqueJobList *--> Job
UniquePersonList --> Person

Person - Job
(Person, Job) .. Employment

Person *--> PersonID
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Address
Person *--> Rate
Person *--> "List<Payment>"

Job *--> JobID
Job *--> Description
Job *--> Duration

@enduml
