@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR
' @@author arrow from nowhere adapted from Anthony-Gaudino
' https://forum.plantuml.net/6378/inwards-outwards-arrow-to-from-a-class-from-to-nowhere
skinparam rectangle {
    BorderColor<<i>> transparent
    FontColor<<i>> transparent
    StereotypeFontColor<<i>> transparent
}

rectangle invis <<i>> {
}
' @@author

package Logic {
Class "<<interface>>\nLogic" as Logic
Class LogicManager
}

package Model{
Class "<<interface>>\nModel" as Model
Class ModelManager
}

package Storage{
Class "<<interface>>\nStorage" as Storage
Class StorageManager
}

invis ..> Logic

LogicManager .up.|> Logic
ModelManager .up.|> Model
StorageManager .up.|> Storage

LogicManager --> Model
LogicManager --> Storage
@enduml
