@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class Person

Class UniqueJobList
Class Job
}

' @@author arrow from nowhere adapted from Anthony-Gaudino
' https://forum.plantuml.net/6378/inwards-outwards-arrow-to-from-a-class-from-to-nowhere
skinparam rectangle {
    BorderColor<<PLACEHOLDER>> transparent
    FontColor<<PLACEHOLDER>> transparent
    StereotypeFontColor<<PLACEHOLDER>> transparent
}

rectangle arrowFromNowhere <<PLACEHOLDER>> {
}
' @@author

arrowFromNowhere ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniquePersonList
UniquePersonList --> "~* all" Person

AddressBook *--> "1" UniqueJobList
UniqueJobList --> "~* all" Job

ModelManager -->"~* filtered" Person
ModelManager -->"~* filtered" Job
@enduml
