@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor MODEL_COLOR

Package Tag <<Rectangle>>{
Class Tag
Class MultiplierTag
}

Tag <|-- MultiplierTag


Tag : isValidTagName()
MultiplierTag : Tag[] elementData
MultiplierTag : size()

@enduml
