@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

' @@author arrow from nowhere adapted from Anthony-Gaudino
' https://forum.plantuml.net/6378/inwards-outwards-arrow-to-from-a-class-from-to-nowhere
skinparam rectangle {
    BorderColor<<i>> transparent
    FontColor<<i>> transparent
    StereotypeFontColor<<i>> transparent
}

rectangle invis <<i>> {
}
' @@author

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class ArgumentMultimap
Class ArgumentTokenizer
Class Prefix
}

invis ..> AddressBookParser

AddressBookParser .down.> XYZCommandParser: creates >

XYZCommandParser ..> XYZCommand : creates >
AddressBookParser ..> Command : returns >
XYZCommandParser .up.|> Parser
XYZCommandParser ..> ArgumentMultimap
XYZCommandParser ..> ArgumentTokenizer
ArgumentTokenizer .left.> ArgumentMultimap
XYZCommandParser ..> CliSyntax
CliSyntax ..> Prefix
XYZCommandParser ..> ParserUtil
ParserUtil .down.> Prefix
ArgumentTokenizer .down.> Prefix
XYZCommand -up-|> Command
@enduml
