/'
 'Commonly used styles and colors across diagrams.
 'Refer to https://plantuml-documentation.readthedocs.io/en/latest for a more
 'comprehensive list of skinparams.
 '/


'T1 through T4 are shades of the original color from lightest to darkest

!define UI_COLOR #92ffc5
!define UI_COLOR_T1 #c5ffe0
!define UI_COLOR_T2 #3dff98
!define UI_COLOR_T3 #00a34c
!define UI_COLOR_T4 #004e25

!define LOGIC_COLOR #958cff
!define LOGIC_COLOR_T1 #d4d0ff
!define LOGIC_COLOR_T2 #766aff
!define LOGIC_COLOR_T3 #4737ff
!define LOGIC_COLOR_T4 #0a007b

!define MODEL_COLOR #95c4ff
!define MODEL_COLOR_T1 #c8e0ff
!define MODEL_COLOR_T2 #62a8ff
!define MODEL_COLOR_T3 #4095ff
!define MODEL_COLOR_T4 #003373

!define STORAGE_COLOR #baff7d
!define STORAGE_COLOR_T1 #e7ffd2
!define STORAGE_COLOR_T2 #9fff4a
!define STORAGE_COLOR_T3 #73f400
!define STORAGE_COLOR_T4 #336c00

!define USER_COLOR #000000
!define LINE_COLOR #444444

skinparam BackgroundColor #FFFFFFF

skinparam Shadowing false

skinparam Class {
    FontColor #000000
    BorderThickness 1
    BorderColor #000000
    StereotypeFontColor #000000
    FontName Arial
}

skinparam Actor {
    BorderColor USER_COLOR
    Color USER_COLOR
    FontName Arial
}

skinparam Sequence {
    MessageAlign center
    BoxFontSize 15
    BoxPadding 0
    BoxFontColor #000000
    FontName Arial
}

skinparam Participant {
    FontColor #000000
    Padding 20
}

skinparam SequenceBoxBorderColor LINE_COLOR
skinparam SequenceLifeLineBorderColor LINE_COLOR
skinparam MinClassWidth 50
skinparam ParticipantPadding 10
skinparam Shadowing false
skinparam DefaultTextAlignment center
skinparam packageStyle Rectangle

hide footbox
hide members
hide circle
