@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow

Class ResultDisplay
Class SideBar
Class CommandBox
Class HelpPage
Class OverviewPage
Class "{abstract}\nPage" as Page

Class PersonListPanel
Class PersonCard
Class JobListPanel
Class JobCard
}

package Model <<Rectangle>> {
Class HiddenModel #FFFFFF
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager -left-|> Ui
UiManager -down-> "1" MainWindow

MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" SideBar
MainWindow *-down-> "1" HelpPage
MainWindow *-down-> "1" OverviewPage

MainWindow --left--|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
SideBar --|> UiPart

OverviewPage --|> Page
HelpPage --|> Page

Page --|> UiPart

OverviewPage *-down-> "1" PersonListPanel
OverviewPage *-down-> "1" JobListPanel

PersonListPanel *-down-> "*" PersonCard
JobListPanel *-down-> "*" JobCard

PersonCard .right.> Model
JobCard .right.> Model
UiManager -right-> Logic
MainWindow -right-> Logic

SideBar -[hidden]right- CommandBox
CommandBox -[hidden]right- ResultDisplay

@enduml
