@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR

' @@author arrow from nowhere adapted from Anthony-Gaudino
' https://forum.plantuml.net/6378/inwards-outwards-arrow-to-from-a-class-from-to-nowhere
skinparam rectangle {
    BorderColor<<b>> transparent
    FontColor<<b>> transparent
    StereotypeFontColor<<b>> transparent
    BorderColor<<i>> transparent
    FontColor<<i>> transparent
    StereotypeFontColor<<i>> transparent
}

rectangle arrowFromNowhere <<b>> {
}
' @@author

package UI <<Rectangle>>{
Class "<<interface>>\nUi" as Ui
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow

Class SideBar
Class PageSwitcher
Class ResultDisplay
Class CommandBox
Class HelpPage
Class OverviewPage
Class "{abstract}\nPage" as Page

PageSwitcher -[hidden]right- MainWindow
PageSwitcher -[hidden]down- SideBar
(MainWindow, SideBar) .. PageSwitcher
Class PersonListPanel
Class PersonCard
Class JobListPanel
Class JobCard
}

package Model <<Rectangle>> {
    ' invisible boxes inside to make the high-level components look bigger
    rectangle a <<i>> {
    }
}

package Logic <<Rectangle>> {
    ' invisible boxes inside to make the high-level components look bigger
    rectangle b <<i>> {
    }
}


arrowFromNowhere ..> Ui

UiManager -left-|> Ui
UiManager -down-> "1" MainWindow

MainWindow *-down-> "1" CommandBox
MainWindow *-down-> "1" ResultDisplay
MainWindow *-down-> "1" SideBar
MainWindow *-down-> "1" HelpPage
MainWindow *-down-> "1" OverviewPage

MainWindow --left--|> UiPart

ResultDisplay --|> UiPart
CommandBox --|> UiPart
SideBar --|> UiPart

OverviewPage --|> Page
HelpPage --|> Page

Page --|> UiPart

OverviewPage *-down-> "1" PersonListPanel
OverviewPage *-down-> "1" JobListPanel

PersonListPanel *-down-> "*" PersonCard
JobListPanel *-down-> "*" JobCard

PersonCard .right.> Model
JobCard .right.> Model
UiManager -right-> Logic
MainWindow -right-> Logic

SideBar -[hidden]right- CommandBox
CommandBox -[hidden]right- ResultDisplay

@enduml
